// <auto-generated />
using System;
using GClaV2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GamesClasificados.Migrations
{
    [DbContext(typeof(GclaDBContext))]
    partial class GclaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GClaV2.Models.Ad", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConsoleId");

                    b.Property<DateTime>("DatePosted");

                    b.Property<string>("Description");

                    b.Property<bool>("Expired");

                    b.Property<string>("ImageUrl");

                    b.Property<long>("OwnerId");

                    b.Property<decimal>("Price");

                    b.Property<int>("SectionId");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Ads");
                });

            modelBuilder.Entity("GClaV2.Models.Section", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("GClaV2.Models.SystemConsole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("SystemConsoles");
                });

            modelBuilder.Entity("GClaV2.Models.User", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<string>("PreferedContactMethod");

                    b.Property<string>("ProfilePictureURL");

                    b.Property<bool>("ShowEmail");

                    b.Property<bool>("ShowPhone");

                    b.Property<string>("Telephone");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.HasAlternateKey("Email");

                    b.ToTable("GClaUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
